version: "2"
output:
  formats:
    tab:
      path: stdout
      print-linter-name: true
      colors: false
linters:
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - durationcheck
    - exhaustive
    - gochecknoinits
    - goconst
    - gocritic
    - gosec
    - lll
    - misspell
    - mnd
    - nakedret
    - noctx
    - nolintlint
    - staticcheck
    - unconvert
    - unparam
  settings:
    goconst:
      min-len: 20
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - mnd
        # Excluding single digits from magic number detector because it produces too many obvious results (like klog)  
        text: 'Magic number: [0-9]{1},'
      - linters:
          - mnd
        # Exclude file masks from magic number detector because these numbers are obvious
        text: 'Magic number: 0[0-7]{3},'
      - linters:
          - mnd
        path: pkg/controllers/proxy/network_services_controller.go
        # Exclude IP masks netmasks as substituting them for constants only makes these less obvious
        text: 'Magic number: 255,'
      - linters:
          - mnd
        # Exclude IP netmasks from magic number detector because these numbers are obvious
        text: 'Magic number: 32,'
      - linters:
          - mnd
        # Exclude decimal bases from magic number detector because these numbers are obvious
        text: 'Magic number: 10,'
      - linters:
          - gosec
        # Exclude file mask security findings as we are always intentional about the file masks we use
        text: 'G306:'
      - linters:
          - lll
        # Exclude tests from long line linter
        path: _test\.go
      - linters:
          - dupl
        # Exclude tests from duplicate linter
        path: _test\.go
      - linters:
          - goconst
        path: (.+)_test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
