builds:
- goos:
  - linux
  goarch:
  - amd64
  env:
  - CGO_ENABLED=0
archive:
  format: tar.gz
  name_template: '{{ .Binary }}_{{.Version}}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{
    .Arm }}{{ end }}'
  files:
  - LICENSE*
  - README*
  - CHANGELOG*
  - Documentation*
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
