name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *'

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: 'This issue is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 5 days.'
          stale-pr-message: 'This PR is stale because it has been open 60 days with no activity. Remove stale label or comment or this will be closed in 10 days.'
          close-issue-message: 'This issue was closed because it has been stale for 5 days with no activity.'
          close-pr-message: 'This PR was closed because it has been stale for 10 days with no activity.'
          days-before-issue-stale: 30
          days-before-pr-stale: 60
          days-before-issue-close: 5
          days-before-pr-close: 10
          exempt-issue-labels: override-stale
          exempt-pr-labels: override-stale,dependencies
          enable-statistics: true
          operations-per-run: 100
